import type { Conversation, Message } from "@/types/api";

// Mock conversations for testing
export const mockConversations: Conversation[] = [
  {
    id: "1",
    contact_id: "whatsapp_5215512345678",
    platform: "whatsapp",
    contact_name: "María García",
    contact_phone: "+52 155 1234 5678",
    last_message: "Hola, quisiera información sobre sus productos de repostería",
    last_message_time: new Date(Date.now() - 1000 * 60 * 5).toISOString(), // 5 min ago
    unread_count: 2,
    conversation_status: "active",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    ai_enabled: true,
  },
  {
    id: "2",
    contact_id: "whatsapp_5215587654321",
    platform: "whatsapp",
    contact_name: "Carlos Rodríguez",
    contact_phone: "+52 155 8765 4321",
    last_message: "Necesito un pedido para mañana, ¿es posible?",
    last_message_time: new Date(Date.now() - 1000 * 60 * 15).toISOString(), // 15 min ago
    unread_count: 1,
    conversation_status: "active",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    ai_enabled: false,
  },
  {
    id: "3",
    contact_id: "whatsapp_5215511223344",
    platform: "whatsapp",
    contact_name: "Ana López",
    contact_phone: "+52 155 1122 3344",
    last_message: "Gracias por la información",
    last_message_time: new Date(Date.now() - 1000 * 60 * 60).toISOString(), // 1 hour ago
    unread_count: 0,
    conversation_status: "active",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    ai_enabled: true,
  },
  {
    id: "4",
    contact_id: "messenger_10215834567890",
    platform: "messenger",
    contact_name: "Roberto Martínez",
    last_message: "¿Tienen servicio a domicilio?",
    last_message_time: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 min ago
    unread_count: 3,
    conversation_status: "active",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    ai_enabled: true,
  },
  {
    id: "5",
    contact_id: "instagram_user123456",
    platform: "instagram",
    contact_name: "Laura Sánchez",
    last_message: "Vi sus productos en Instagram, me interesa el catálogo",
    last_message_time: new Date(Date.now() - 1000 * 60 * 45).toISOString(), // 45 min ago
    unread_count: 1,
    conversation_status: "active",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    ai_enabled: false,
  },
  {
    id: "6",
    contact_id: "messenger_10215899999999",
    platform: "messenger",
    contact_name: "Patricia Fernández",
    last_message: "Buenos días, ¿cuáles son sus horarios de entrega?",
    last_message_time: new Date(Date.now() - 1000 * 60 * 10).toISOString(), // 10 min ago
    unread_count: 2,
    conversation_status: "active",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    ai_enabled: true,
  },
  {
    id: "7",
    contact_id: "instagram_user789012",
    platform: "instagram",
    contact_name: "Diego Morales",
    last_message: "¿Hacen descuentos por volumen?",
    last_message_time: new Date(Date.now() - 1000 * 60 * 20).toISOString(), // 20 min ago
    unread_count: 0,
    conversation_status: "active",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    ai_enabled: true,
  },
  {
    id: "8",
    contact_id: "messenger_10215877777777",
    platform: "messenger",
    contact_name: "Alejandra Torres",
    last_message: "Me gustaría hacer un pedido especial para un evento",
    last_message_time: new Date(Date.now() - 1000 * 60 * 90).toISOString(), // 1.5 hours ago
    unread_count: 0,
    conversation_status: "active",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    ai_enabled: false,
  },
  {
    id: "9",
    contact_id: "instagram_user345678",
    platform: "instagram",
    contact_name: "Sofía Ramírez",
    last_message: "¿Tienen opciones veganas?",
    last_message_time: new Date(Date.now() - 1000 * 60 * 120).toISOString(), // 2 hours ago
    unread_count: 1,
    conversation_status: "active",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    ai_enabled: true,
  },
  {
    id: "10",
    contact_id: "facebook_10215866666666",
    platform: "facebook",
    contact_name: "Miguel Hernández",
    last_message: "Vi su anuncio en Facebook, quisiera más información",
    last_message_time: new Date(Date.now() - 1000 * 60 * 35).toISOString(), // 35 min ago
    unread_count: 4,
    conversation_status: "active",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    ai_enabled: true,
  },
];

// Mock messages for each conversation
export const mockMessages: Record<string, Message[]> = {
  "whatsapp_5215512345678": [
    {
      id: 1,
      message_id: "msg_1",
      platform: "whatsapp",
      from_number: "+52 155 1234 5678",
      to_number: "business",
      direction: "incoming",
      message_content: "Hola, buenas tardes",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      read: true,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
    {
      id: 2,
      message_id: "msg_2",
      platform: "whatsapp",
      from_number: "business",
      to_number: "+52 155 1234 5678",
      direction: "outgoing",
      message_content: "¡Hola! Bienvenido a Capriccio. ¿En qué puedo ayudarte hoy?",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
      read: true,
      status: "read",
      ai_enabled: true,
      ai_response_generated: true,
    },
    {
      id: 3,
      message_id: "msg_3",
      platform: "whatsapp",
      from_number: "+52 155 1234 5678",
      to_number: "business",
      direction: "incoming",
      message_content: "Quisiera información sobre sus productos de repostería",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
      read: true,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
    {
      id: 4,
      message_id: "msg_4",
      platform: "whatsapp",
      from_number: "business",
      to_number: "+52 155 1234 5678",
      direction: "outgoing",
      message_content: "Con mucho gusto. Contamos con una amplia variedad de productos:\n\n🍰 Pasteles personalizados\n🧁 Cupcakes\n🍪 Galletas artesanales\n🥐 Pan dulce\n🎂 Pasteles de celebración\n\n¿Hay algo en particular que te interese?",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      read: true,
      status: "read",
      ai_enabled: true,
      ai_response_generated: true,
    },
    {
      id: 5,
      message_id: "msg_5",
      platform: "whatsapp",
      from_number: "+52 155 1234 5678",
      to_number: "business",
      direction: "incoming",
      message_content: "Me interesan los pasteles personalizados",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      read: false,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
    {
      id: 6,
      message_id: "msg_6",
      platform: "whatsapp",
      from_number: "+52 155 1234 5678",
      to_number: "business",
      direction: "incoming",
      message_content: "Hola, quisiera información sobre sus productos de repostería",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      read: false,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
  ],
  "whatsapp_5215587654321": [
    {
      id: 7,
      message_id: "msg_7",
      platform: "whatsapp",
      from_number: "+52 155 8765 4321",
      to_number: "business",
      direction: "incoming",
      message_content: "Buenas tardes",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      read: true,
      status: "delivered",
      ai_enabled: false,
      ai_response_generated: false,
    },
    {
      id: 8,
      message_id: "msg_8",
      platform: "whatsapp",
      from_number: "business",
      to_number: "+52 155 8765 4321",
      direction: "outgoing",
      message_content: "Buenas tardes, ¿en qué puedo ayudarte?",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
      read: true,
      status: "read",
      ai_enabled: false,
      ai_response_generated: false,
    },
    {
      id: 9,
      message_id: "msg_9",
      platform: "whatsapp",
      from_number: "+52 155 8765 4321",
      to_number: "business",
      direction: "incoming",
      message_content: "Necesito un pedido para mañana, ¿es posible?",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      read: false,
      status: "delivered",
      ai_enabled: false,
      ai_response_generated: false,
    },
  ],
  "whatsapp_5215511223344": [
    {
      id: 10,
      message_id: "msg_10",
      platform: "whatsapp",
      from_number: "+52 155 1122 3344",
      to_number: "business",
      direction: "incoming",
      message_content: "Hola, ¿cuáles son sus horarios?",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      read: true,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
    {
      id: 11,
      message_id: "msg_11",
      platform: "whatsapp",
      from_number: "business",
      to_number: "+52 155 1122 3344",
      direction: "outgoing",
      message_content: "Nuestros horarios son:\n\nLunes a Viernes: 9:00 AM - 7:00 PM\nSábados: 9:00 AM - 5:00 PM\nDomingos: 10:00 AM - 3:00 PM",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
      read: true,
      status: "read",
      ai_enabled: true,
      ai_response_generated: true,
    },
    {
      id: 12,
      message_id: "msg_12",
      platform: "whatsapp",
      from_number: "+52 155 1122 3344",
      to_number: "business",
      direction: "incoming",
      message_content: "Gracias por la información",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      read: true,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
  ],
  "messenger_10215834567890": [
    {
      id: 13,
      message_id: "msg_13",
      platform: "messenger",
      from_number: "Roberto Martínez",
      to_number: "business",
      direction: "incoming",
      message_content: "Hola",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
      read: false,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
    {
      id: 14,
      message_id: "msg_14",
      platform: "messenger",
      from_number: "Roberto Martínez",
      to_number: "business",
      direction: "incoming",
      message_content: "¿Tienen servicio a domicilio?",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      read: false,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
  ],
  "instagram_user123456": [
    {
      id: 15,
      message_id: "msg_15",
      platform: "instagram",
      from_number: "Laura Sánchez",
      to_number: "business",
      direction: "incoming",
      message_content: "Vi sus productos en Instagram, me interesa el catálogo",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      read: false,
      status: "delivered",
      ai_enabled: false,
      ai_response_generated: false,
    },
  ],
  "messenger_10215899999999": [
    {
      id: 16,
      message_id: "msg_16",
      platform: "messenger",
      from_number: "Patricia Fernández",
      to_number: "business",
      direction: "incoming",
      message_content: "Buenos días",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
      read: true,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
    {
      id: 17,
      message_id: "msg_17",
      platform: "messenger",
      from_number: "business",
      to_number: "Patricia Fernández",
      direction: "outgoing",
      message_content: "¡Buenos días Patricia! Bienvenida a Capriccio. ¿En qué puedo ayudarte?",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
      read: true,
      status: "read",
      ai_enabled: true,
      ai_response_generated: true,
    },
    {
      id: 18,
      message_id: "msg_18",
      platform: "messenger",
      from_number: "Patricia Fernández",
      to_number: "business",
      direction: "incoming",
      message_content: "¿cuáles son sus horarios de entrega?",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      read: false,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
  ],
  "instagram_user789012": [
    {
      id: 19,
      message_id: "msg_19",
      platform: "instagram",
      from_number: "Diego Morales",
      to_number: "business",
      direction: "incoming",
      message_content: "Hola, necesito hacer un pedido grande",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      read: true,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
    {
      id: 20,
      message_id: "msg_20",
      platform: "instagram",
      from_number: "business",
      to_number: "Diego Morales",
      direction: "outgoing",
      message_content: "¡Hola Diego! Claro, con gusto te ayudo. ¿Para cuántas personas aproximadamente?",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
      read: true,
      status: "read",
      ai_enabled: true,
      ai_response_generated: true,
    },
    {
      id: 21,
      message_id: "msg_21",
      platform: "instagram",
      from_number: "Diego Morales",
      to_number: "business",
      direction: "incoming",
      message_content: "¿Hacen descuentos por volumen?",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
      read: true,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
  ],
  "messenger_10215877777777": [
    {
      id: 22,
      message_id: "msg_22",
      platform: "messenger",
      from_number: "Alejandra Torres",
      to_number: "business",
      direction: "incoming",
      message_content: "Me gustaría hacer un pedido especial para un evento",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
      read: true,
      status: "delivered",
      ai_enabled: false,
      ai_response_generated: false,
    },
    {
      id: 23,
      message_id: "msg_23",
      platform: "messenger",
      from_number: "business",
      to_number: "Alejandra Torres",
      direction: "outgoing",
      message_content: "¡Hola Alejandra! Por supuesto, hacemos pedidos especiales. ¿Qué tipo de evento es y para cuándo lo necesitas?",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
      read: true,
      status: "read",
      ai_enabled: false,
      ai_response_generated: false,
    },
  ],
  "instagram_user345678": [
    {
      id: 24,
      message_id: "msg_24",
      platform: "instagram",
      from_number: "Sofía Ramírez",
      to_number: "business",
      direction: "incoming",
      message_content: "Hola! ¿Tienen opciones veganas?",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      read: false,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
  ],
  "facebook_10215866666666": [
    {
      id: 25,
      message_id: "msg_25",
      platform: "facebook",
      from_number: "Miguel Hernández",
      to_number: "business",
      direction: "incoming",
      message_content: "Vi su anuncio en Facebook",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
      read: false,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
    {
      id: 26,
      message_id: "msg_26",
      platform: "facebook",
      from_number: "Miguel Hernández",
      to_number: "business",
      direction: "incoming",
      message_content: "quisiera más información",
      message_type: "text",
      timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
      created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
      read: false,
      status: "delivered",
      ai_enabled: true,
      ai_response_generated: false,
    },
  ],
};

// Helper function to get mock messages for a conversation
export function getMockMessages(contactId: string): Message[] {
  return mockMessages[contactId] || [];
}

// Helper function to simulate API delay
export function simulateApiDelay(ms: number = 500): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}